export default [
  {
    id: 1,
    name: "Marble Queen Pothos",
    price: 18,
    img: "./public/marble_queen.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },

  {
    id: 2,
    name: "Cylindrical Snake Plant",
    price: 15,
    img: "./public/cylindrical_snake_plant.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },

  {
    id: 3,
    name: "Boston Fern",
    price: 12,
    img: "./public/boston-fern.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },

  {
    id: 4,
    name: "Haworthia",
    price: 15,
    img: "./public/succulent-haworthia.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: true,
  },
  {
    id: 5,
    name: "Parlor Palm",
    price: 9,
    img: "./public/parlor-palm.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: true,
  },

  {
    id: 6,
    name: "Peace Lily",
    price: 15,
    img: "./public/peace-lily.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },
  {
    id: 7,
    name: "Curly Spider Plant",
    price: 27,
    img: "./public/curly-spider-plant.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },
  {
    id: 8,
    name: "Corn Plant",
    price: 35,
    img: "./public/corn-plant.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },

  {
    id: 9,
    name: "Snake Plant",
    price: 20,
    img: "./public/snake-plant.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },
  {
    id: 10,
    name: "Aspidistra",
    price: 27,
    img: "./public/aspidistra.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },
  {
    id: 11,
    name: "Monstera",
    price: 35,
    img: "./public/monstera.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: false,
  },

  {
    id: 12,
    name: "Maranta",
    price: 20,
    img: "./public/maranta.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },
  {
    id: 13,
    name: "Peperomia",
    price: 13,
    img: "./public/peperomia.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },
  {
    id: 14,
    name: "Chinese Money Plant",
    price: 16,
    img: "./public/money-plant.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },

  {
    id: 15,
    name: "Ficus Ginseng",
    price: 44,
    img: "./public/ficus-ginseng.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: false,
  },
  {
    id: 16,
    name: "Zamioculcas",
    price: 31,
    img: "./public/zamioculcas.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },
  {
    id: 17,
    name: "Philodendron",
    price: 18,
    img: "./public/philodendron.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: false,
  },

  {
    id: 18,
    name: "Dwarf Fan Palm",
    price: 38,
    img: "./public/dwarf-fan-palm.jpg",
    description: "",
    isFavorite: false,
    forBeginners: true,
    isPetSafe: false,
  },
  {
    id: 19,
    name: "Calathea",
    price: 20,
    img: "./public/calathea.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },
  {
    id: 20,
    name: "Maidenhair Fern",
    price: 20,
    img: "./public/maidenhair-fern.jpg",
    description: "",
    isFavorite: false,
    forBeginners: false,
    isPetSafe: true,
  },
];
